---
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: '{{ visual_studio_code_package_state }}'

# Required for Visual Studio Code account login on crostini.
# See https://github.com/microsoft/vscode-docker/issues/1515.
- name: install gnome-keyring for vscode on crostini
  become: yes
  apt:
    name: gnome-keyring
    state: present
  when: ansible_facts['product_name'] == 'crosvm'

- name: install key (apt)
  become: yes
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    state: '{{ visual_studio_code_package_state_simple }}'

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64{{ visual_studio_code_gpgcheck | ternary("", " trusted=yes") }}] {{ visual_studio_code_mirror }}/repos/code stable main'
    filename: vscode
    state: '{{ visual_studio_code_package_state_simple }}'
  when: not visual_studio_code_skip_add_repo

- name: install VS Code (apt)
  become: yes
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: '{{ visual_studio_code_package_state }}'
