---
- name: install dependencies (zypper)
  become: yes
  zypper:
    name:
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
      - libxshmfence1
      - which
    state: '{{ visual_studio_code_package_state }}'

- name: install key (zypper)
  become: yes
  rpm_key:
    state: '{{ visual_studio_code_package_state_simple }}'
    key: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'

- name: write repo configuration (zypper)
  become: yes
  template:
    src: vscode.repo.j2
    dest: '/etc/zypp/repos.d/vscode.repo'
    mode: 'u=rw,go='
    owner: root
    group: root
  when: not visual_studio_code_skip_add_repo

- name: install VS Code (zypper)
  become: yes
  zypper:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: '{{ visual_studio_code_package_state }}'
